# Don't run Azure when a branch is updated, only when a PR is updated.
# Prevents double builds when a PR is made from the main repo and not a fork.
trigger: none
pr:
  autoCancel: true
  branches:
    include:
    - '*'

pool:
  # self-hosted agent on Windows 10 1709 environment
  # includes newer Docker engine with LCOW enabled, new build of LCOW image
  # includes Ruby 2.5, Go 1.10, Node.js 10.10, hadolint
  name: Default

variables:
  NAMESPACE: puppet

steps:
- checkout: self
  clean: true
- powershell: |
    $gemfile = Join-Path -Path (Get-Location) -ChildPath 'docker/Gemfile'
    $gempath = Join-Path -Path (Get-Location) -ChildPath 'docker/.bundle/gems'
    bundle config --local gemfile $gemfile
    bundle config --local path $gempath
    bundle install
  displayName: Fetch Dependencies
  name: fetch_deps
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Write-HostDiagnostics
  displayName: Diagnostic Host Information
  name: hostinfo
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Lint-Dockerfile -Name puppetserver-standalone -Ignore @('DL3028')
  displayName: Lint PuppetServer-Standalone Dockerfile
  name: lint_puppetserverstandalone_dockerfile
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Lint-Dockerfile -Name puppetserver -Ignore @('DL3028')
  displayName: Lint PuppetServer Dockerfile
  name: lint_puppetserver_dockerfile
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Build-Container -Name puppetserver-standalone -Namespace $ENV:NAMESPACE -Context . -AdditionalOptions @('--memory', '4g')
  displayName: Build PuppetServer-Standalone Container
  name: build_puppetserverstandalone_container
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Build-Container -Name puppetserver -Namespace $ENV:NAMESPACE -Pull $false -AdditionalOptions @('--memory', '4g')
  displayName: Build PuppetServer Container
  name: build_puppetserver_container
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Invoke-ContainerTest -Name puppetserver-standalone -Namespace $ENV:NAMESPACE -Options puppetserver-standalone/.rspec
  displayName: Test PuppetServer-Standalone
  name: test_puppetserverstandalone
- task: PublishTestResults@2
  displayName: Publish PuppetServer Standalone Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'docker/puppetserver-standalone/TEST-*.xml'
    testRunTitle: PuppetServer-Standalone Test Results
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Invoke-ContainerTest -Name puppetserver -Namespace $ENV:NAMESPACE -Options puppetserver/.rspec
  displayName: Test PuppetServer
  name: test_puppetserver
- task: PublishTestResults@2
  displayName: Publish PuppetServer Test Results
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'docker/puppetserver/TEST-*.xml'
    testRunTitle: PuppetServer Test Results
- powershell: |
    . "$(bundle show pupperware)/ci/build.ps1"
    Clear-ContainerBuilds -Name puppetserver -Namespace $ENV:NAMESPACE
    Clear-ContainerBuilds -Name puppetserver-standalone -Namespace $ENV:NAMESPACE
  displayName: Container Cleanup
  name: cleanup_containers
  condition: always()
