pe-and-platform/puppetserver:
  PreBuild:
    - bundle install --path .bundle/gems
    - bundle exec ci/pre_build
  Build:
    - bundle exec ci/build
    - bundle exec ci/test
  AfterBuildSuccess:
    - bundle exec ci/publish
